### ISSUE TITLE
【MIN】Gathering Will be stuck in one place

### ISSUE THREAD

**Issue by PaSSw0rds** [y2krazy/Rebornbuddy-Profiles#45]
**Place:**
in Gate of   Thal (Central Thanalan)
**Where:**
_<189.8025, 6.117051, 988.6992> to <189.7353, 6.117051, 988.3063>_
**profile:**
[O] [MIN] Leveling 1-70 + 1-60 Quests.xml
**pic:**
https://s1.ax1x.com/2018/03/01/9re1eK.jpg
**Problems:**
People continue to move around，But can not reach the target location

**Comment by kannad** [comment]
This bug has been reproduced many times
Hm..My English is bad so maybe expression is not in place
There are bugs when trying to reach the target spot on the left and there is no problem on the right
